### ISSUE TITLE
OS Compatibility

### ISSUE THREAD

**Issue by xLinkKnight** [bittremieux/ANN-SoLo#15]
May I ask if ANN-SoLo has been tested using Windows? Is it strictly compatible with Linux?

**Comment by bittremieux** [comment]
Unfortunately the current version (v.0.3.3) only works on Unix (Linux / OS X) due to limitations of software dependencies that we use. Some of these dependencies have matured since then, so we want to try to release a fully cross-platform version in the (nearish) future. At the moment, this is not officially supported yet though, but stay tuned.
